  version: '3.9'

  services:

    db:
      image: postgres:15.3
      container_name: postgres_db
      restart: on-failure
      volumes:
        - ./postgres:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: "django_user"
        POSTGRES_PASSWORD: "django_password"
        POSTGRES_DB: "django_db"
        TZ: "Europe/Moscow"
      ports:
        - 5432:5432
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready" ]
        interval: 2s
        timeout: 1s
        retries: 5
        start_period: 1s

    web:
      build: ./django_app
      container_name: django
      restart: on-failure
      command: sh -c "python manage.py migrate && python manage.py createsuperuser --noinput --username admin --email admin@example.com || echo 'Superuser already exists, skipping creation' && gunicorn django_app.wsgi:application --bind 0.0.0.0:8000"
      environment:
        - DJANGO_SUPERUSER_USERNAME=admin
        - DJANGO_SUPERUSER_PASSWORD=admin
        - DJANGO_SUPERUSER_EMAIL=admin@example.com
      volumes:
        - ./django_app/:/usr/src/app/
        - ./django_app/static/:/usr/src/app/static/
        - ./django_app/media/:/usr/src/app/media/
      expose:
        - 8000
      ports:
      - 8000:8000
      env_file:
        - ./.env.dev
      depends_on:
        - db
    nginx:
      build: ./nginx
      container_name: nginx
      ports:
        - 8080:80
      depends_on:
        - web
      volumes:
        - ./django_app/static/:/usr/src/app/static/
        - ./django_app/media/:/usr/src/app/media/
  volumes:
    postgres:
    static_volume:
    media_volume:
